In [1]:
import numpy as np
import xarray as xr

import sys
sys.path.append('../')

from ERA import ERA_Fields_New as ef

In this environment you cannot import Basemap
In this environment you cannot import Basemap


In [13]:
#tas = ef.Plasim_Field('tas', 'tas.nc', label='2m temperature', Model='Plasim', mylocal='../../EW2-heatwaves/data/') # on MAC
tas = ef.Plasim_Field('tas', 'Data_Plasim/tas.nc', label='2m temperature', Model='Plasim',)

In [3]:
tas.field

<xarray.DataArray 'tas' (time: 150000, lat: 64, lon: 128)>
[1228800000 values with dtype=float32]
Coordinates:
  * time     (time) object 0000-05-01 10:30:00 ... 0999-09-30 10:30:00
  * lon      (lon) float64 0.0 2.812 5.625 8.438 ... 348.8 351.6 354.4 357.2
  * lat      (lat) float64 87.86 85.1 82.31 79.53 ... -79.53 -82.31 -85.1 -87.86
Attributes:
    standard_name:  air_temperature_2m
    long_name:      air_temperature_2m
    units:          K
    code:           167

In [4]:
tas.field.time.dt.year

<xarray.DataArray 'year' (time: 150000)>
array([  0,   0,   0, ..., 999, 999, 999])
Coordinates:
  * time     (time) object 0000-05-01 10:30:00 ... 0999-09-30 10:30:00

In [14]:
tas.select_years(list(np.arange(10)))

In [15]:
tas.select_lonlat(lat_end=22, lon_start=64, lon_end=64)

In [7]:
tas.field

<xarray.DataArray 'tas' (time: 1500, lat: 22, lon: 128)>
array([[[259.04596, 259.01904, 258.98923, ..., 259.1083 , 259.09045,
         259.0694 ],
        [262.11682, 262.1571 , 262.18268, ..., 261.8964 , 261.9868 ,
         262.0609 ],
        [266.6684 , 266.98526, 267.26218, ..., 265.39972, 265.8703 ,
         266.29434],
        ...,
        [286.5143 , 286.49405, 286.3439 , ..., 288.091  , 287.30457,
         286.71646],
        [289.7262 , 289.95157, 290.18054, ..., 290.41306, 289.9675 ,
         289.72552],
        [292.14505, 292.33145, 292.8862 , ..., 292.8586 , 292.68353,
         292.43063]],

       [[266.1622 , 266.153  , 266.13486, ..., 266.1379 , 266.1542 ,
         266.16235],
        [269.2423 , 269.38345, 269.49658, ..., 268.65897, 268.87775,
         269.0744 ],
        [271.84296, 272.26443, 272.60263, ..., 270.09244, 270.75757,
         271.34155],
...
        [293.10767, 293.23355, 293.54437, ..., 294.81085, 294.13828,
         293.43878],
        [296.17834, 296.31528, 296.38794, ..., 297.15924, 296.88626,
         296.39645],
        [297.55002, 297.5225 , 297.46942, ..., 297.8859 , 297.95416,
         297.7715 ]],

       [[271.53717, 271.5152 , 271.49347, ..., 271.5993 , 271.5792 ,
         271.55838],
        [271.41562, 271.3757 , 271.33548, ..., 271.52673, 271.49115,
         271.45425],
        [271.47986, 271.4401 , 271.4024 , ..., 271.61713, 271.56955,
         271.52295],
        ...,
        [293.72946, 292.80136, 291.8004 , ..., 296.08368, 295.4036 ,
         294.5634 ],
        [296.41638, 295.95648, 295.5097 , ..., 297.43542, 297.38416,
         296.9613 ],
        [297.6128 , 297.48236, 297.51804, ..., 298.07962, 298.3093 ,
         298.07886]]], dtype=float32)
Coordinates:
  * time     (time) object 0000-05-01 10:30:00 ... 0009-09-30 10:30:00
  * lon      (lon) float64 180.0 182.8 185.6 188.4 ... 168.8 171.6 174.4 177.2
  * lat      (lat) float64 87.86 85.1 82.31 79.53 ... 37.67 34.88 32.09 29.3
Attributes:
    standard_name:  air_temperature_2m
    long_name:      air_temperature_2m
    units:          K
    code:           167

In [16]:
tas.set_mask('France')

In [17]:
tas.filter()

In [10]:
tas.mask.shape

(22, 128)

In [14]:
tas.mask

<xarray.DataArray 'lsm' (time: 720, lat: 22, lon: 128)>
array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
...
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]])
Coordinates:
  * lon      (lon) float64 180.0 182.8 185.6 188.4 ... 168.8 171.6 174.4 177.2
  * lat      (lat) float64 87.86 85.1 82.31 79.53 ... 37.67 34.88 32.09 29.3
  * time     (time) object 0001-01-01 00:00:00 ... 0001-01-30 23:00:00
Attributes:
    long_name:      land_binary_mask
    standard_name:  land_binary_mask
    units:          1
    code:           172
    grid_type:      gaussian

In [23]:
lsm = ef.get_lsm(mylocal='/local/gmiloshe/PLASIM/', Model='Plasim')

In [19]:
lsm.dims

('time', 'lat', 'lon')

In [11]:
tas.field.data *= tas.mask.data

In [12]:
tas.filter()