In [1]:
import sys
sys.path.append('../')
import ERA.utilities as ut
import logging
from functools import wraps
import ast
import numpy as np
import Learn2_new as ln
import inspect
from stat import S_IREAD

In this environment you cannot import Basemap
In this environment you cannot import Basemap


In [2]:
import tensorflow as tf

In [3]:
Y_pred = np.array([[1., 0], [0.5,0.5], [0.2,0.3]])
Y_pred_tf = tf.convert_to_tensor([[1., 0], [0.5,0.5], [0.2,0.3]])

2022-01-31 11:07:33.767429: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-01-31 11:07:33.770214: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-31 11:07:33.773160: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [5]:
a = tf.zeros_like(Y_pred_tf)

In [6]:
np.clip(Y_pred_tf, 0.1, 0.9)

array([[0.9, 0.1],
       [0.5, 0.5],
       [0.2, 0.3]], dtype=float32)

In [4]:
ut.unbias_probabilities(Y_pred_tf, u=10, backend='tf')

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [2]:
inspect.signature(ln.load_data).parameters.items()

odict_items([('dataset_years', <Parameter "dataset_years=1000">), ('year_list', <Parameter "year_list=None">), ('sampling', <Parameter "sampling=''">), ('Model', <Parameter "Model='Plasim'">), ('area', <Parameter "area='France'">), ('filter_area', <Parameter "filter_area='France'">), ('lon_start', <Parameter "lon_start=0">), ('lon_end', <Parameter "lon_end=128">), ('lat_start', <Parameter "lat_start=0">), ('lat_end', <Parameter "lat_end=22">), ('mylocal', <Parameter "mylocal='/local/gmiloshe/PLASIM/'">), ('fields', <Parameter "fields=['t2m', 'zg500', 'mrso_filtered']">)])

In [2]:
logger = logging.getLogger()
logger.handlers = [logging.StreamHandler(sys.stdout)]

In [4]:
logger == logging.getLogger(logger.name)

True

In [3]:
@ut.indent_logger(logger)
def test():
    logger.critical('test')

In [6]:
logger.error('error')
test()
logger.error('error2')

error
	test
error2


In [5]:
logger.handlers.append(logging.FileHandler('log.log', 'a'))

In [10]:
stream_handler = logging.StreamHandler(sys.stdout)
stream_handler.setFormatter(logging.Formatter('%(levelname)s : %(message)s'))
file_handler = logging.FileHandler('log.log')
file_handler.setFormatter(ut.default_formatter)

In [19]:
lg = logging.getLogger('altlg')
# lg.handlers = [stream_handler]
lg.level = 30

In [24]:
import telegram_handler
help(telegram_handler.handlers.TelegramHandler)

Help on class TelegramHandler in module telegram_handler.handlers:

class TelegramHandler(logging.Handler)
 |  TelegramHandler(token, chat_id=None, level=0, timeout=2, disable_notification=False, disable_web_page_preview=False, proxies=None)
 |  
 |  Method resolution order:
 |      TelegramHandler
 |      logging.Handler
 |      logging.Filterer
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, token, chat_id=None, level=0, timeout=2, disable_notification=False, disable_web_page_preview=False, proxies=None)
 |      Initializes the instance - basically setting the formatter to None
 |      and the filter list to empty.
 |  
 |  emit(self, record)
 |      Do whatever it takes to actually log the specified logging record.
 |      
 |      This version is intended to be implemented by subclasses and so
 |      raises a NotImplementedError.
 |  
 |  get_chat_id(self)
 |  
 |  request(self, method, **kwargs)
 |  
 |  send_document(self, text, document, **kwargs)

In [20]:
lg.warning('From altlg')

In [11]:
logger.handlers = [stream_handler, file_handler, th]

In [6]:
logging.basicConfig(level=logging.INFO, handlers=[
        stream_handler,
        file_handler,
        th,
    ])
# logging.basicConfig()

In [31]:
filename = 't.txt'
with open(filename, 'w') as f:
    f.write('Hi')

In [16]:
logging.log(10, 'Hallo')

In [3]:
@ut.indent_stdout
def bul():
    print('Printing')
    logging.critical('logging critical message')
    print('Printing 2')
    logging.critical('logging 2')
    print('Printing 3')
    logging.critical('logging 3')
    # logging.info('logging info')

In [4]:
print('print before')
logging.log(50, 'before')
bul()
print('print after')
logging.warning('after')
print('print after 2')
logging.critical('log after 2')

print before
CRITICAL:root:before
	Printing
CRITICAL:root:logging critical message
	Printing 2
CRITICAL:root:logging 2
	Printing 3
CRITICAL:root:logging 3
print after
print after 2
CRITICAL:root:log after 2


In [3]:
logger = logging.getLogger()

In [4]:
logger.handlers

[<StreamHandler stdout (NOTSET)>,
 <FileHandler /media/alessandro/OS/Users/ale57/Documents/0. Lyon/WORK/Climate-Learning/PLASIM/log.log (NOTSET)>]

In [6]:
logger.handlers[1].stream.write


<function TextIOWrapper.write(text, /)>

In [2]:
logging.root.manager.loggerDict

{'concurrent.futures': <Logger concurrent.futures (WARNING)>,
 'concurrent': <logging.PlaceHolder at 0x7fb5696fc070>,
 'asyncio': <Logger asyncio (WARNING)>,
 'tornado.access': <Logger tornado.access (WARNING)>,
 'tornado': <Logger tornado (WARNING)>,
 'tornado.application': <Logger tornado.application (WARNING)>,
 'tornado.general': <Logger tornado.general (WARNING)>,
 'prompt_toolkit.buffer': <Logger prompt_toolkit.buffer (WARNING)>,
 'prompt_toolkit': <logging.PlaceHolder at 0x7fb5681b9a60>,
 'parso.python.diff': <Logger parso.python.diff (WARNING)>,
 'parso.python': <logging.PlaceHolder at 0x7fb567c9e250>,
 'parso': <logging.PlaceHolder at 0x7fb567c9e2b0>,
 'parso.cache': <Logger parso.cache (WARNING)>,
 'IPKernelApp': <Logger IPKernelApp (WARNING)>}

In [1]:
import os
from pathlib import Path
import ast
import sys
sys.path.append('../')
import ERA.utilities as ut
import Learn2_new as ln
import traceback


In this environment you cannot import Basemap
In this environment you cannot import Basemap


In [3]:
help(ln.Trainer.prepare_XY)

Help on function prepare_XY in module Learn2_new:

prepare_XY(fields, make_XY_kwargs=None, roll_X_kwargs=None, do_premix=False, premix_seed=0, do_balance_folds=True, nfolds=10, year_permutation=None, flatten_time_axis=True)
    Performs all operations to extract from the fields X and Y ready to be fed to the neural network.
    
    Parameters
    ----------
    fields : dict of ef.Plasim_Field objects
    make_XY_kwargs : dict
        arguments to pass to the function `make_XY`
    roll_X_kwargs : dict
        arguments to pass to the function `roll_X`
    do_premix : bool, optional
        whether to perform premixing, by default False
    premix_seed : int, optional
        seed for premixing, by default 0
    do_balance_folds : bool, optional
        whether to balance folds
    nfolds : int, optional
        necessary for balancing folds
    year_permutation : np.ndarray, optional
        if provided overrides both premixing and fold balancing, useful for transfer learning as avoi

In [6]:
os.access(f"{os.environ['HOME']}/ENSMLbot.txt", os.R_OK)

True

In [2]:
l = ast.literal_eval('hello')
l

ValueError: malformed node or string: <ast.Name object at 0x7f9622e58c10>

In [22]:
type(l[0])

int

In [23]:
ut.dict2json({'l': l[0], }, 't.json')

In [25]:
t = ln.Trainer()

FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

In [32]:
try:
    raise ValueError('Not provided')
except Exception as e:
    v = traceback.format_exc()
    print(f'{v = }')
    print(repr(e), type(repr(e)))
    raise e

v = 'Traceback (most recent call last):\n  File "/var/folders/p8/k08kk0c517zd64tyd8q0vqw80000gp/T/ipykernel_1181/2418270265.py", line 2, in <module>\n    raise ValueError(\'Not provided\')\nValueError: Not provided\n'
ValueError('Not provided') <class 'str'>


ValueError: Not provided

In [37]:
summary = '\n'
def summary_printer(x):
    global summary
    summary += x + '\n'

In [40]:
summary

'\nHi\n'

In [39]:
summary_printer('Hi')

In [15]:
a = '0--tau__[1,2,3]'
a = a.replace('[', '\[')
a = a.replace(']', '\]')

In [21]:
a = [[1,2,3], [4,5,6]]
s = str(a)
s = s.replace(' ','')
s = s.replace('[','')
s = s.replace('],', ',,')
s = s.replace(']', '')
s

'1,2,3,,4,5,6'

In [3]:
repr(a)

"'0--tau__[1,2,3]'"

In [1]:
import numpy as np

In [3]:
-np.sort(-np.arange(5))

array([4, 3, 2, 1, 0])

In [5]:
def bias(p0, r):
    return p0/(p0 + r*(1-p0))

def unbias(p0t, r):
    return r*p0t/(1 - (1 - r)*p0t)

In [8]:
r = 10
p0 = 0.9

p0t = bias(p0,r)
p0n = unbias(p0t,r)
print(p0, p0t, p0n)

0.9 0.4736842105263158 0.9


In [10]:
a = np.array([[0,1], [0.1, 0.9], [1,0]])
np.clip(a, 0.01, 0.99)

array([[0.01, 0.99],
       [0.1 , 0.9 ],
       [0.99, 0.01]])

In [20]:
import numpy as np
import sys
sys.path.append('../ERA')
import ERA_Fields_New as ef

In this environment you cannot import Basemap


In [42]:
a = ['1', 1, 0, None, {'a': '12'}]
a.index({'a': '12'})

4

In [44]:
a = {'1': {'tau': 0, 'percent': 1}, '2': {'tau': -5, 'size': (2,5)}, '3':{'tau':-5, 'percent':1}}
taus = {k:v.pop('tau') for k,v in a.items()}
print(taus)
print(a)
group_args = []
group_runs = []
for k,v in a.items():
    try:
        i = group_args.index(v)
        group_runs[i].append(k)
    except ValueError:
        group_args.append(v)
        group_runs.append([k])

print(group_args)
print(group_runs)
        

{'1': 0, '2': -5, '3': -5}
{'1': {'percent': 1}, '2': {'size': (2, 5)}, '3': {'percent': 1}}
[{'percent': 1}, {'size': (2, 5)}]
[['1', '3'], ['2']]


In [14]:
a = np.arange(0,1,0.1)
np.c_[a, 1-a]

array([[0. , 1. ],
       [0.1, 0.9],
       [0.2, 0.8],
       [0.3, 0.7],
       [0.4, 0.6],
       [0.5, 0.5],
       [0.6, 0.4],
       [0.7, 0.3],
       [0.8, 0.2],
       [0.9, 0.1]])

In [6]:
Y_pred = np.array([0, 1])
Y_pred_prob = np.array([[0.1,0.9], [0.9, 0.1]])

np.mean(ef.entropy(1 - Y_pred, Y_pred_prob[:,0]))

2.302585092994046

In [12]:
ef.entropy(0.05)

0.1985152433458726

In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame({'fold_0': {'a': 0, 'b': 1}, 'fold_1': {'a': 0.5, 'b': 0.5}}).T
df

a    b
fold_0  0.0  1.0
fold_1  0.5  0.5

In [5]:
df['a']

fold_0    0.0
fold_1    0.5
Name: a, dtype: float64

In [9]:
df.loc['mean'] = df.mean()

In [10]:
df

a     b
fold_0  0.00  1.00
fold_1  0.50  0.50
mean    0.25  0.75

In [11]:
df['a']['mean']

0.25

In [18]:
a = {'1': {'tau': 0}}
b = a.copy()

In [2]:
for v in a.values():
    v['p'] = 'l'

In [17]:
def f(a):
    _a = a.copy()
    for k,v in _a.items():
        _a[k]['p'] = 'l'

In [19]:
f(a)
a

{'1': {'tau': 0, 'p': 'l'}}

In [15]:
for v in a.values():
    v['b'] = 'l'

In [16]:
print(a)
print(b)

{'1': {'tau': 0, 'b': 'l'}, '2': {'percent': 5, 'b': 'l'}}
{'1': {'tau': 0, 'b': 'l'}}


In [6]:
from ast import literal_eval
import numpy as np

In [19]:
literal_eval('(0,5,2)')

(0, 5, 2)

In [7]:

np.array(range(0,10,2))

array([0, 2, 4, 6, 8])

In [10]:
np.arange(1,5,2)

array([1, 3])

In [23]:
year_list = 'range(0,5,2)'
args = year_list.split('(',1)[1].split(')',1)[0].split(',')
args = tuple(int(arg) for arg in args)
print(args)
year_list = np.arange(*args)
year_list

(0, 5, 2)


array([0, 2, 4])

In [22]:
tuple([a for a in np.arange(2)])

(0, 1)

In [25]:
tuple(2)

TypeError: 'int' object is not iterable