In [2]:
import numpy as np

In [5]:
a = np.arange(20)
p = a/np.sum(a)

In [12]:
np.random.choice(a,size=19,replace=True, p=p)

array([19, 18,  5,  9, 16, 10,  9, 14, 19, 18, 19, 19, 15, 15, 15,  5, 12,
       17, 18])

In [15]:
def select(*arrays, amount=0.1, p=None):
    l = len(arrays[0])
    for a in arrays[1:]:
        if l != len(a):
            raise ValueError(f'Arrays with different lengths: {[len(a) for a in arrays]}')
    if p is not None and p.shape != (l,):
        raise ValueError(f'p must be a 1D array with the same length as the provided arrays ({l})')
    if isinstance(amount, float):
        if amount < 0 or amount > 1:
            raise ValueError('Amount must be either int or float between 0 and 1')
        amount = int(l*amount)

    indexes = np.arange(l)
    selected_indexes = np.random.choice(indexes, size=amount, replace=False, p=p)
    remaining_indexes = np.delete(indexes, selected_indexes)

    output = []
    for a in arrays:
        output += a[selected_indexes], a[remaining_indexes]

    return output


In [23]:
select(np.arange(100), np.arange(100)**2, amount=0.001, p=np.arange(100)/(50*99))

[array([], dtype=int64),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([], dtype=int64),
 array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
         121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
         484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
        1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
        1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
        3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
        4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 

In [34]:
a = np.random.uniform(0,1,(10, 2,3))
b = np.random.uniform(0,1,(3, 2,3))
np.concatenate([a[0:0], a, b]).shape

(13, 2, 3)

In [4]:
a = ['aaa', 'baa', 'gulb']
all([s.startswith('aa') for s in a])

False

In [3]:
bool('')

False

In [2]:
'aaabbaaa'.strip('a')

'bb'