In [18]:
def myFun(k=2,**kwargs):
    if 'first' in (kwargs.keys()):
        print(kwargs
              ['first'])
    print("k = ", k)
myFun(first='1')

1
k =  2


In [22]:
myFun(2, first='1')

1
k =  2


In [1]:
import numpy as np

In [6]:
year_permutation1 = np.load('xforanalogs/NA24by48/Z8/yrs500/interT15fw20.1.20kl.5.5lrs4/fold_0/year_permutation_va.npy')
year_permutation2 = np.load('xforanalogs/NA24by48/Z8/yrs500/interT15fw20.1.20lrs4/fold_0/year_permutation_va.npy')
np.max(year_permutation1-year_permutation2)

0

In [8]:
time_series_tr = np.load('xforanalogs/NA24by48/Z8/yrs500/interT15fw20.1.20kl.5.5lrs4/fold_0/time_series_tr.npy')
time_series_va = np.load('xforanalogs/NA24by48/Z8/yrs500/interT15fw20.1.20kl.5.5lrs4/fold_0/time_series_va.npy')
print(time_series_tr.shape,time_series_va.shape)

(47250, 3) (5250, 3)


In [14]:
5250/50

105.0

In [24]:
import sys
sys.path.insert(1, '../ERA')

import ERA_Fields as ef # general routines
import TF_Fields as tff # tensorflow routines
import utilities as ut


In this environment you cannot import Basemap


Trying to import basemap
In this environment you cannot import Basemap
Trying to import cartopy
Successfully imported cartopy


2022-02-10 11:00:53.406182: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [25]:
encoder_inputs, encoder_outputs, shape_before_flattening, encoder  = tff.build_encoder2(input_dim = (24, 128, 3), 
                                                output_dim = 64, 
                                                conv_filters = [32, 64, 64, 64],
                                                conv_kernel_size = [3,3,3,3],
                                                conv_strides = [2,2,2,1],
                                                conv_padding = ["same","same","same","valid"], 
                                                conv_activation = ["LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu"],use_batch_norm=True, use_dropout=True)

0
1
2
3
shape_before_flattening =  (1, 14, 64)
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
encoder input (InputLayer)      [(None, 24, 128, 3)] 0                                            
_______________________________________

2022-02-10 11:03:51.745237: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-10 11:03:51.746648: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-02-10 11:03:51.746677: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-10 11:03:51.746719: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (r740server5): /proc/driver/nvidia/version does not exist
2022-02-10 11:03:51.747090: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebui

In [26]:
decoder_input, decoder_output, decoder = tff.build_decoder2(input_dim = 64,  
                                        shape_before_flattening = shape_before_flattening,
                                        conv_filters = [64,64,32,3],
                                        conv_kernel_size = [3,3,3,3],
                                        conv_strides = [1,2,2,2],
                                        conv_padding = ["valid","same","same","same"], 
                                        conv_activation = ["LeakyRelu","LeakyRelu","LeakyRelu","linear"])

In [28]:
vae = tff.VAE(encoder, decoder, k1=0.9, k2=0.1, from_logits=False)

TypeError: ('Keyword argument not understood:', 'from_logits')

In [49]:
import tensorflow as tf
import numpy as np
y_true = [[0.1, 0.9], [0.4, 0.6]]
y_pred = [[0.6, 0.4], [0.4, 0.6]]
loss = tf.keras.losses.binary_crossentropy(y_true, y_pred)
print(y_true,y_pred,loss)

[[0.1, 0.9], [0.4, 0.6]] [[0.6, 0.4], [0.4, 0.6]] tf.Tensor([0.875744  0.6730114], shape=(2,), dtype=float32)


In [46]:
y_true = [[0.4, 0.6]]
y_pred = [[0.4, 0.6]]
loss = tf.keras.losses.binary_crossentropy(y_true, y_pred, from_logits=True)
print(y_true,y_pred,loss)

[[0.4, 0.6]] [[0.4, 0.6]] tf.Tensor([0.7152516], shape=(1,), dtype=float32)


In [41]:
-0.4*np.log(0.4)+0.6*np.log(0.6)

0.6730116670092565

In [50]:
y_true = [0, 1, 0, 0]
y_pred = [-18.6, 0.51, 2.94, -12.8]
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True)
bce(y_true, y_pred).numpy()

0.865458

In [70]:
bce([-0.1, 1, 0.1, 0.1],[-18.6, 0.51, 2.94, -12.8]).numpy()

0.646958

In [61]:
bceF = tf.keras.losses.BinaryCrossentropy(from_logits=False)

In [83]:
bceF([.5, 1, 0, 1], [0.1, 0.9, 0.5, 0.5]).numpy()

0.6739067

In [97]:
list(map(tff.logit,[0.1, 0.9, 0.5, 0.5]))

[<tf.Tensor: shape=(), dtype=float32, numpy=-1.0986123>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0986123>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.0>]

In [84]:
np.mean(list(np.sum(map(lambda x, y: -(x)*np.log(y)-(1-x)*np.log(1-y), [.5, 1, 0, 1], [0.1, 0.9, 0.5, 0.5]))))

0.6739069202759133

In [88]:
print( tf.keras.losses.binary_crossentropy([.5, 1, 0, 1], [0.1, 0.9, 0.5, 0.5]).numpy() )

0.6739067


In [89]:
tff.logit(1)

<tf.Tensor: shape=(), dtype=float32, numpy=inf>

In [1]:
import tensorflow as tf
import numpy as np
#tf.enable_eager_execution() # This command is deprecated, use the one below
#tf.compat.v1.enable_eager_execution()
from tensorflow import keras
from tensorflow.keras import regularizers
from tensorflow.keras.layers import Dense, Activation, Flatten, Conv2D, SeparableConv2D, MaxPooling2D, BatchNormalization, Dropout, SpatialDropout2D, Input, concatenate, Softmax, Reshape, Add, Conv2DTranspose, LeakyReLU # Vallerian's approach
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras import datasets, layers, models # from https://www.tensorflow.org/tutorials/images/cnn
from tensorflow.keras import backend as K
class Sampling(tf.keras.layers.Layer):  # Normal distribution sampling for the encoder output of the variational autoencoder
    """Uses (z_mean, z_log_var) to sample z, the vector encoding a digit."""

    def call(self, inputs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon
    
def build_encoder_skip(input_dim, output_dim, conv_filters, conv_kernel_size, conv_strides, conv_padding, conv_activation, conv_skip, use_batch_norm = False, use_dropout = False):
    # Number of Conv layers
    n_layers = len(conv_filters)
    encoder_inputs = tf.keras.Input(shape=input_dim, name ='encoder input')
    
    x = []
    x.append(encoder_inputs)
    # Add convolutional layers
    for i in range(n_layers):
        print(i, f"Conv2D, filters = {conv_filters[i]}, kernel_size = {conv_kernel_size[i]}, strides = {conv_strides[i]}, padding = {conv_padding[i]}")
        conv = Conv2D(filters = conv_filters[i], 
                kernel_size = conv_kernel_size[i],
                strides = conv_strides[i], 
                padding = conv_padding[i],
                name = 'encoder_conv_' + str(i))(x[i])

        if use_batch_norm:
            conv = BatchNormalization()(conv)
            print("conv = BatchNormalization()(conv)")
            
        if conv_activation[i] == 'LeakyRelu':
            actv = LeakyReLU()(conv)
            print("actv = LeakyReLU()(conv)")
        else:
            actv = Activation(conv_activation[i])(conv)
            print("actv = Activation(conv_activation[i])(conv)")

        if use_dropout:
            actv = Dropout(rate=0.25)(actv)
            print("actv = Dropout(rate=0.25)(actv)")
        
        if i in conv_skip.values(): # The arrow of the skip connection end here
            print('conv = keras.layers.add([conv, arrow_start])')
            actv = keras.layers.add([actv, arrow_start])
            if use_batch_norm:
                actv = BatchNormalization()(actv)
                print("actv = BatchNormalization()(actv)")
        
        if i in conv_skip.keys(): # The arrow of the skip connection starts here
            print('arrow_start = actv')
            arrow_start = actv
        
        x.append(actv)
        

    shape_before_flattening = K.int_shape(x[-1])[1:] 
    print("shape_before_flattening = ", shape_before_flattening)
    x.append(tf.keras.layers.Flatten()(x[-1]))
    z_mean = tf.keras.layers.Dense(output_dim, name="z_mean")(x[-1])
    z_log_var = tf.keras.layers.Dense(output_dim, name="z_log_var")(x[-1])
    z = Sampling()([z_mean, z_log_var])
    encoder_outputs = [z_mean, z_log_var, z]
    encoder = tf.keras.Model(encoder_inputs, encoder_outputs, name="encoder")
    return encoder_inputs, encoder_outputs,  shape_before_flattening, encoder

INPUT_DIM =  (24, 128, 3)
Z_DIM = 64

encoder_inputs, encoder_outputs, shape_before_flattening, encoder  = build_encoder_skip(input_dim = INPUT_DIM, 
                                                output_dim = Z_DIM, 
                                                conv_filters =     [16, 16, 16, 32, 32,  32,   64, 64],
                                                conv_kernel_size = [5,  5,  5,  5,   5,   5,   5,  3],
                                                conv_strides =     [2,  1,  1,  2,   1,   1,   2,  1],
                                                conv_padding =     ["same","same","same","same","same","same","same","valid"], 
                                                conv_activation =  ["LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu"],
                                                #conv_skip = dict({}),use_batch_norm=True, use_dropout=True)
                                                conv_skip = dict({(0,2),(3,5)}),use_batch_norm=True, use_dropout=True)
encoder.summary()

2022-02-17 08:54:04.004215: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


0 Conv2D, filters = 16, kernel_size = 5, strides = 2, padding = same
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
arrow_start = actv
1 Conv2D, filters = 16, kernel_size = 5, strides = 1, padding = same
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
2 Conv2D, filters = 16, kernel_size = 5, strides = 1, padding = same
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
conv = keras.layers.add([conv, arrow_start])
actv = BatchNormalization()(actv)
3 Conv2D, filters = 32, kernel_size = 5, strides = 2, padding = same
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
arrow_start = actv
4 Conv2D, filters = 32, kernel_size = 5, strides = 1, padding = same
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
5 Conv2D, filters = 32, kernel_size = 5, strides = 1, padding = same
conv = BatchNo

2022-02-17 08:54:12.105123: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-17 08:54:12.105356: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-02-17 08:54:12.105365: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-17 08:54:12.105379: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (r740server5): /proc/driver/nvidia/version does not exist
2022-02-17 08:54:12.105542: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebui

In [2]:
def build_decoder_skip(input_dim, shape_before_flattening, conv_filters, conv_kernel_size, conv_strides,conv_padding, conv_activation, conv_skip, use_batch_norm = False, use_dropout = False):
    # Number of Conv layers
    n_layers = len(conv_filters)
    decoder_inputs = tf.keras.Input(shape=input_dim)
    
    x = []
    
    x.append(tf.keras.layers.Dense(tf.math.reduce_prod(shape_before_flattening), activation="relu")(decoder_inputs))
    x[0] = tf.keras.layers.Reshape(shape_before_flattening)(x[0])
    
    
    # Add convolutional layers
    for i in range(n_layers):
        print(i, f"Conv2D, filters = {conv_filters[i]}, kernel_size = {conv_kernel_size[i]}, strides = {conv_strides[i]}, padding = {conv_padding[i]}")
        conv = Conv2DTranspose(filters = conv_filters[i], 
                            kernel_size = conv_kernel_size[i],
                            strides = conv_strides[i], 
                            padding = conv_padding[i],
                            name = 'decoder_conv_' + str(i))(x[i])
        
        if use_batch_norm:
            conv = BatchNormalization()(conv)
            print("conv = BatchNormalization()(conv)")
            
        if conv_activation[i] == 'LeakyRelu':
            actv = LeakyReLU()(conv)
            print("actv = LeakyReLU()(conv)")
        else:
            actv = Activation(conv_activation[i])(conv)
            print("actv = Activation(conv_activation[i])(conv)")
            
        if use_dropout:
            actv = Dropout(rate=0.25)(actv)
            print("actv = Dropout(rate=0.25)(actv)")
        
        if i in conv_skip.values(): # The arrow of the skip connection end here
            print('conv = keras.layers.add([conv, arrow_start])')
            actv = keras.layers.add([actv, arrow_start])
            if use_batch_norm:
                actv = BatchNormalization()(actv)
                print("actv = BatchNormalization()(actv)")
        
        if i in conv_skip.keys(): # The arrow of the skip connection starts here
            print('arrow_start = actv')
            arrow_start = actv
        
        x.append(actv)
        

    decoder_outputs = x[-1]
    decoder = tf.keras.Model(decoder_inputs, decoder_outputs, name="decoder")
    decoder.summary()
    return decoder_inputs, decoder_outputs, decoder  

decoder_input, decoder_output, decoder = build_decoder_skip(input_dim = Z_DIM,  
                                        shape_before_flattening = shape_before_flattening,
                                        conv_filters =     [64,32,32,32,16,16,16,3],
                                        conv_kernel_size = [3, 5, 5, 5, 5, 5, 5, 5],
                                        conv_strides =     [1, 2, 1, 1, 2, 1, 1, 2],
                                        conv_padding =     ["valid","same","same","same","same","same","same","same"], 
                                        conv_activation =  ["LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu","LeakyRelu","sigmoid"], 
                                                              conv_skip = dict({(1,3),(4,6)}), use_batch_norm = True, use_dropout = True)

0 Conv2D, filters = 64, kernel_size = 3, strides = 1, padding = valid
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
1 Conv2D, filters = 32, kernel_size = 5, strides = 2, padding = same
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
arrow_start = actv
2 Conv2D, filters = 32, kernel_size = 5, strides = 1, padding = same
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
3 Conv2D, filters = 32, kernel_size = 5, strides = 1, padding = same
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
conv = keras.layers.add([conv, arrow_start])
actv = BatchNormalization()(actv)
4 Conv2D, filters = 16, kernel_size = 5, strides = 2, padding = same
conv = BatchNormalization()(conv)
actv = LeakyReLU()(conv)
actv = Dropout(rate=0.25)(actv)
arrow_start = actv
5 Conv2D, filters = 16, kernel_size = 5, strides = 1, padding = same
conv = BatchN

In [3]:
class VAE(tf.keras.Model): # Class of variational autoencoder
    def __init__(self, encoder, decoder, k1=1, k2=1, from_logits=False, **kwargs):
        super(VAE, self).__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.k1 = k1
        self.k2 = k2
        self.total_loss_tracker = tf.keras.metrics.Mean(name="total_loss")
        self.reconstruction_loss_tracker = tf.keras.metrics.Mean(
            name="reconstruction_loss"
        )
        self.kl_loss_tracker = tf.keras.metrics.Mean(name="kl_loss")
        self.from_logits = from_logits
        print("VAE: self.from_logits = ", self.from_logits)

    @property
    def metrics(self):
        return [
            self.total_loss_tracker,
            self.reconstruction_loss_tracker,
            self.kl_loss_tracker,
        ]
    def call(self, inputs):
        _, _, z =  self.encoder(inputs)
        return self.decoder(z)

    def train_step(self, data):
        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)
            reconstruction_loss = self.k1*tf.reduce_mean(
                tf.reduce_sum(
                    tf.keras.losses.binary_crossentropy(data, reconstruction, from_logits=self.from_logits), axis=(1, 2) # -Y_n Log( P_n) - (1 - Y_n) Log( 1 - P_n) is the expression for binary entropy
                )
            )
            kl_loss = -0.5 * (1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var))
            kl_loss = self.k2*tf.reduce_mean(tf.reduce_sum(kl_loss, axis=1))
            total_loss = reconstruction_loss + kl_loss
        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))
        self.total_loss_tracker.update_state(total_loss)
        self.reconstruction_loss_tracker.update_state(reconstruction_loss)
        self.kl_loss_tracker.update_state(kl_loss)
        return {
            "loss": self.total_loss_tracker.result(),
            "reconstruction_loss": self.reconstruction_loss_tracker.result(),
            "kl_loss": self.kl_loss_tracker.result(),
        }


In [4]:
vae = VAE(encoder, decoder, k1=0.9, k2=0.1, from_logits=False)
print("vae.k1 = ", vae.k1, " , vae.k2 = ", vae.k2)

VAE: self.from_logits =  False
vae.k1 =  0.9  , vae.k2 =  0.1


In [118]:
INPUT_DIM_withnone = list(INPUT_DIM)
INPUT_DIM_withnone.insert(0,None)

vae.build(tuple(INPUT_DIM_withnone)) 
vae.compute_output_shape(tuple(INPUT_DIM_withnone))
vae.summary(line_length=250)

Model: "vae_2"
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
Layer (type)                                                                                                    Output Shape                                                                                        Param #                               
encoder (Functional)                                                                                            [(None, 64), (None, 64), (None, 64)]                                                                235920                                
________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

In [125]:
X = np.random.rand(12000,24,128,3)

In [126]:
vae.compile(optimizer=tf.keras.optimizers.Adam(lr = 1e-3))
vae.fit(X)

375/375 [==============================] - 21s 52ms/step - loss: 1916.4172 - reconstruction_loss: 1916.4193 - kl_loss: 2.2231e-05


In [8]:
samples, timesteps, features = 1, 10, 8
inputs = np.random.random([samples, timesteps, features]).astype(np.float32)
inputs[:, 3, :] = 0.
inputs[:, 5, :] = 0.

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Masking(mask_value=0.,
                                  input_shape=(timesteps, features)))
output = model(inputs)

In [9]:
inputs

array([[[0.46128374, 0.9001634 , 0.04844501, 0.73280776, 0.26635328,
         0.5908927 , 0.30841282, 0.48893222],
        [0.31458378, 0.96840477, 0.9637747 , 0.06462356, 0.6331117 ,
         0.8372965 , 0.45977703, 0.44410992],
        [0.20960408, 0.09524056, 0.26436535, 0.66635215, 0.16854256,
         0.09905799, 0.4028925 , 0.4379977 ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.46829778, 0.706549  , 0.7080177 , 0.9993042 , 0.7820028 ,
         0.7262145 , 0.7611772 , 0.8496592 ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.63751245, 0.45891994, 0.47536567, 0.3227062 , 0.7916975 ,
         0.10720778, 0.7190421 , 0.8173516 ],
        [0.5572264 , 0.3897331 , 0.978318  , 0.9555788 , 0.80107224,
         0.66683614, 0.62790656, 0.09479985],
        [0.2924169 , 0.76012915, 0.6209345 , 0.69279367, 0.9869724 ,
         0.

In [10]:
output

<tf.Tensor: shape=(1, 10, 8), dtype=float32, numpy=
array([[[0.46128374, 0.9001634 , 0.04844501, 0.73280776, 0.26635328,
         0.5908927 , 0.30841282, 0.48893222],
        [0.31458378, 0.96840477, 0.9637747 , 0.06462356, 0.6331117 ,
         0.8372965 , 0.45977703, 0.44410992],
        [0.20960408, 0.09524056, 0.26436535, 0.66635215, 0.16854256,
         0.09905799, 0.4028925 , 0.4379977 ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.46829778, 0.706549  , 0.7080177 , 0.9993042 , 0.7820028 ,
         0.7262145 , 0.7611772 , 0.8496592 ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.63751245, 0.45891994, 0.47536567, 0.3227062 , 0.7916975 ,
         0.10720778, 0.7190421 , 0.8173516 ],
        [0.5572264 , 0.3897331 , 0.978318  , 0.9555788 , 0.80107224,
         0.66683614, 0.62790656, 0.09479985],
        [0.2924169 , 0.76012

In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

2022-02-15 12:51:06.125555: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [12]:
[
  ["Hello", "world", "!"],
  ["How", "are", "you", "doing", "today"],
  ["The", "weather", "will", "be", "nice", "tomorrow"],
]

[['Hello', 'world', '!'],
 ['How', 'are', 'you', 'doing', 'today'],
 ['The', 'weather', 'will', 'be', 'nice', 'tomorrow']]

In [14]:
raw_inputs = [
    [711, 632, 71],
    [73, 8, 3215, 55, 927],
    [83, 91, 1, 645, 1253, 927],
]

# By default, this will pad using 0s; it is configurable via the
# "value" parameter.
# Note that you could "pre" padding (at the beginning) or
# "post" padding (at the end).
# We recommend using "post" padding when working with RNN layers
# (in order to be able to use the
# CuDNN implementation of the layers).
padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
    raw_inputs, padding="post"
)
print(padded_inputs)

[[ 711  632   71    0    0    0]
 [  73    8 3215   55  927    0]
 [  83   91    1  645 1253  927]]


In [17]:
embedding = layers.Embedding(input_dim=5000, output_dim=16, mask_zero=True)
masked_output = embedding(padded_inputs)

print("masked_output._keras_mask = ", masked_output._keras_mask)

masking_layer = layers.Masking()
# Simulate the embedding lookup by expanding the 2D input to 3D,
# with embedding dimension of 10.
unmasked_embedding = tf.cast(
    tf.tile(tf.expand_dims(padded_inputs, axis=-1), [1, 1, 10]), tf.float32
)

masked_embedding = masking_layer(unmasked_embedding)
print("masked_embedding._keras_mask = ", masked_embedding._keras_mask)

masked_output._keras_mask =  tf.Tensor(
[[ True  True  True False False False]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]], shape=(3, 6), dtype=bool)
masked_embedding._keras_mask =  tf.Tensor(
[[ True  True  True False False False]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]], shape=(3, 6), dtype=bool)


In [42]:
tf.matmul(decoder(np.random.rand(2,64)), tf.cast(np.random.rand(2,24,128,3), dtype=np.float32))

InvalidArgumentError: In[0] mismatch In[1] shape: 3 vs. 128: [2,24,128,3] [2,24,128,3] 0 0 [Op:BatchMatMulV2]

In [37]:
decoder(np.random.rand(2,64)).shape

TensorShape([2, 24, 128, 3])

In [43]:
tf.cast(np.random.rand(2,24,128,3), dtype=np.float32).shape

TensorShape([2, 24, 128, 3])

In [12]:
(decoder(np.random.rand(2,64))* tf.cast(np.random.rand(1,24,128,1), dtype=np.float32))

<tf.Tensor: shape=(2, 24, 128, 3), dtype=float32, numpy=
array([[[[0.2577511 , 0.2578477 , 0.25784737],
         [0.34136993, 0.34129468, 0.3414165 ],
         [0.24401249, 0.24416268, 0.24396709],
         ...,
         [0.03379441, 0.03385627, 0.03380223],
         [0.45199803, 0.45210332, 0.45205176],
         [0.41098303, 0.41098854, 0.4111942 ]],

        [[0.23611483, 0.23616387, 0.23602559],
         [0.00775513, 0.00775773, 0.00776956],
         [0.26924306, 0.26929867, 0.26977754],
         ...,
         [0.3729346 , 0.37337252, 0.3738026 ],
         [0.24861783, 0.24802993, 0.2485212 ],
         [0.49903235, 0.49904644, 0.5007119 ]],

        [[0.3295082 , 0.32976946, 0.32963583],
         [0.33412915, 0.33331215, 0.3340564 ],
         [0.3038749 , 0.3044882 , 0.30416763],
         ...,
         [0.13201503, 0.13206002, 0.13198419],
         [0.18280387, 0.18323576, 0.18328637],
         [0.48631704, 0.48613024, 0.48651353]],

        ...,

        [[0.16314329, 0.1632284 , 0

In [7]:
A = tf.cast(np.random.rand(1,2,3,1), dtype=np.float32)
B = tf.cast(np.random.rand(4,2,3,5), dtype=np.float32)

In [8]:
sample_weights=np.ones((2,4,3))

In [4]:
data = np.random.rand(2,4,3,3)
reconstruction = np.random.rand(2,4,3,3)

tf.reduce_mean(tf.cast([1,1,1], dtype=np.float64)*tf.cast([ tf.reduce_mean(tf.keras.losses.binary_crossentropy(data[...,i], reconstruction[...,i], from_logits=False)) for i in range(reconstruction.shape[3])], dtype=np.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=1.0009096630773833>

In [5]:
tf.reduce_mean(tf.cast([ tf.reduce_mean(tf.keras.losses.binary_crossentropy(data[...,i], reconstruction[...,i], from_logits=False)) for i in range(reconstruction.shape[3])], dtype=np.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=1.0009096630773833>

In [15]:
bce = tf.keras.losses.BinaryCrossentropy(from_logits=False)
weight = [0.1,0.1,0.4]
tf.reduce_mean([weight[i]*bce(data[...,i], reconstruction[...,i]) for i in range(3)])

<tf.Tensor: shape=(), dtype=float64, numpy=0.20403463045756023>

In [16]:
bce = tf.keras.losses.BinaryCrossentropy(from_logits=False)
tf.reduce_mean([0.1,0.1,0.4]*tf.cast([bce(data[...,i][..., np.newaxis], reconstruction[...,i][..., np.newaxis],sample_weight=np.ones((2,4,3))) for i in range(3)], dtype=np.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20403461>

In [18]:
np.ones((2,4,3))*np.array([[0,0,0],[0,1,0],[0,1,0],[0,0,0]])

array([[[0., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 0.]]])

In [13]:
tf.reduce_mean(
                tf.reduce_sum(
                    tf.keras.losses.binary_crossentropy(data, reconstruction, from_logits=False), axis=(1, 2) # -Y_n Log( P_n) - (1 - Y_n) Log( 1 - P_n) is the expression for binary entropy
                )
            )

<tf.Tensor: shape=(), dtype=float64, numpy=7.114887712258982>

In [18]:
tf.keras.losses.binary_crossentropy(data, reconstruction, from_logits=False).shape

TensorShape([4, 2, 3])

In [67]:
tf.keras.losses.binary_crossentropy(data, reconstruction, from_logits=False)

<tf.Tensor: shape=(4, 2, 3), dtype=float64, numpy=
array([[[0.75726913, 0.89669753, 0.63865613],
        [0.81066815, 0.93738841, 0.80784008]],

       [[0.7057068 , 0.9447314 , 0.5589693 ],
        [0.75710092, 0.79151364, 0.83299612]],

       [[0.9114958 , 1.22730784, 0.79311213],
        [0.72786358, 0.66081091, 1.12107577]],

       [[0.58690855, 0.78219115, 0.69134229],
        [1.13746031, 1.13786584, 0.67024675]]])>

In [68]:
tf.keras.losses.binary_crossentropy(data, reconstruction, from_logits=False).shape

TensorShape([4, 2, 3])

In [5]:
def create_mask(model,area, data, axes='first 2', return_full_mask=False): # careful, this mask works if we load the full Earth. there might be problems if we extract fields from some edge of the map
    """
    This function allows to extract a subset of data enclosed in the area.
    The output has the dimension of the area on the axes corresponding to latitued and longitude
    If the area includes the Greenwich meridian, a concatenation is required.
    
    If `axes` == 'last 2', the slicing will be done on the last 2 axes,
    otherwise on the first two axes
    
    If `return_full_mask` == True, the function returns an array with the same shape of `data`, True over the `area` and False elsewhere
    Otherwise the return will be `data` restricted to `area`
    """
    
    if axes == 'first 2' and len(data.shape) > 2:
        # permute the shape so that the first 2 axes end up being the last 2
        _data = data.transpose(*range(2,len(data.shape)),0,1)
        _data = create_mask(model, area, _data, axes='last 2', return_full_mask=return_full_mask)
        # permute the axes back to their original condition
        return _data.transpose(-2, -1, *range(len(data.shape) - 2))
    
    if return_full_mask:
        mask = np.zeros_like(data, dtype=bool)
    
    if model == "ERA5":
        if area == "Scandinavia":
            if return_full_mask:
                mask[...,25:45,7:53] = True
                return mask
            return data[...,25:45,7:53]# reconstructed from Francesco
        elif area == "Scand": # = Norway Sweden
            if return_full_mask:
                mask[...,25:45,7:30] = True
                return mask
            return data[...,25:45,7:30]
        elif area == "NAtlantic":
            if return_full_mask:
                mask[...,25:80, -135:] = True
                mask[...,25:80, :60] = True
                return mask
            return np.concatenate((data[...,25:80, -135:], data[...,25:80, :60]), axis=-1)  # used for plotting
        elif area == "France":
            if return_full_mask:
                mask[...,51:63, -4:] = True
                mask[...,51:63, :9] = True
                return mask
            return np.concatenate((data[...,51:63, -4:], data[...,51:63, :9]), axis=-1)  # reconstructed from Francesco
        elif area == "France_bis":
            if return_full_mask:
                mask[...,52:64, -5:] = True
                mask[...,52:64, :9] = True
                return mask
            return np.concatenate((data[...,52:64, -5:], data[...,52:64, :9]), axis=-1)  # fixing to CESM
        elif area == "Russia":  # lat[i]<60 and lat[i]>50: index 9-15
            if return_full_mask:
                mask[...,37:60, 42:79] = True
                return mask
            return data[...,37:60, 42:79] 
        elif area == "Poland":  # From stefanon
            if return_full_mask:
                mask[...,44:60, 18:43] = True
                return mask
            return data[...,44:60, 18:43]
        else:
            print(f'Unknown area {area}')
            return None
    elif model == "CESM":
        if area == "France":
            if return_full_mask:
                mask[...,-51:-41, -3:] = True
                mask[...,-51:-41, :6] = True
                return mask
            return np.concatenate((data[...,-51:-41, -3:],data[...,-51:-41, :6]), axis=-1)
        elif area == "Scandinavia":
            if return_full_mask:
                mask[...,-36:-20, 4:32] = True
                return mask
            return data[...,-36:-20, 4:32]
        elif area == "Scand": # = Norway Sweden
            if return_full_mask:
                mask[...,-36:-20, 4:18] = True
                return mask
            return data[...,-36:-20, 4:18]
        elif area == "Russia":  # lat[i]<60 and lat[i]>50: index 9-15
            if return_full_mask:
                mask[...,-48:-29, 25:48] = True
                return mask
            return data[...,-48:-29, 25:48]  # lon[i]<55 and lon[i]>35:   index 11-21
        elif area == "Poland":  # From Stefanon
            if return_full_mask:
                mask[...,-48:-35, 11:26] = True
                return mask
            return data[...,-48:-35, 11:26]
        else:
            print(f'Unknown area {area}')
            return None
    elif model == "Plasim":
        if area == "NW_Europe":
            if return_full_mask:
                mask[...,10:16, -1:] = True
                mask[...,10:16, :7] = True
                return mask
            return np.concatenate((data[...,10:16, -1:], data[...,10:16, :7]), axis=-1)  # give by Valerian/Francesco 
        elif area == "Greenland":
            if return_full_mask:
                mask[...,2:9, 108:120] = True
                return mask
            return data[...,2:9, 108:120]
        elif area == "Europe":
            if return_full_mask:
                mask[...,7:19, -3:] = True
                mask[...,7:19, :10] = True
                return mask
            return np.concatenate((data[...,7:19, -3:], data[...,7:19, :10]), axis=-1)  # give by Valerian/Francesco  
        elif area == "France":
            if return_full_mask:
                mask[...,13:17, -1:] = True
                mask[...,13:17, :3] = True
                return mask
            return np.concatenate((data[...,13:17, -1:], data[...,13:17, :3]), axis=-1)  # give by valerian
        elif area == "Quebec":  # lat[i]<60 and lat[i]>50:      index: 10-13
            if return_full_mask:
                mask[...,10:16, 98:110] = True
                return mask
            return data[...,10:16, 98:110]  # lon[i]<180+120 and lon[i]>180+110   index:104-106
        elif area == "USA":  # lat[i]<50 and lat[i]>25:  index: 14-22
            if return_full_mask:
                mask[...,14:23, 89:109] = True
                return mask
            return data[...,14:23, 89:109]  # lon[i]<180+125 and lon[i]>180+70:  index 89-108
        elif area == "US":  # lat[i]<50 and lat[i]>25:  index: 14-22   # < fixing the area of philipinne
            if return_full_mask:
                mask[...,14:23, 84:104] = True
                return mask
            return data[...,14:23, 84:104]  # lon[i]<180+125 and lon[i]>180+70:  index 89-108
        elif area == "Midwest":
            if return_full_mask:
                mask[...,16:20, 92:99] = True
                return mask
            return data[...,16:20, 92:99]
        elif area == "Alberta":
            if return_full_mask:
                mask[...,10:15, 85:90] = True
                return mask
            return data[...,10:15, 85:90]
        elif area == "Scandinavia":  # 55<lat<72: index: 6-11
            if return_full_mask:
                mask[...,6:12, 2:15] = True
                return mask
            return data[...,6:12, 2:15]  # 5<lon<40 : index 2-14
        elif area == "Scand":  #  = Norway Sweden
            if return_full_mask:
                mask[...,6:12, 2:8] = True
                return mask
            return data[...,6:12, 2:8]  # 5<lon<40 : index 2-14
        elif area == "Russia":  # lat[i]<60 and lat[i]>50: index 9-15
            if return_full_mask:
                mask[...,9:16, 11:22] = True
                return mask
            return data[...,9:16, 11:22]  # lon[i]<55 and lon[i]>35:   index 11-21
        elif area == "Poland":  # lat[i]<60 and lat[i]>50: index 9-15
            if return_full_mask:
                mask[...,11:16, 5:12] = True
                return mask
            return data[...,11:16, 5:12]  # lon[i]<55 and lon[i]>35:   index 11-21
        elif area == 'total':  # return all data, use for total_area function and create surface over continents
            if return_full_mask:
                return np.ones_like(data, dtype=bool)
            return data
        else:
            print(f'Unknown area {area}')
            return None
    else:
        print(f'Unknown model {model}')
        return None

In [6]:
def roll_X(X, roll_axis='lon', roll_steps=64):
    '''
    Rolls `X` along a given axis. useful for example for moving France away from the Greenwich meridian.
    In other words this allows one, for example, to shift the grid so that desired areas are not found at the boundary.
    In principle this function allows us to roll along arbitrary axis, including days or years.

    Parameters
    ----------
    X : np.ndarray
        with shape (years, days, lat, lon, field)
    axis : str, optional
        'year' (or 'y'), 'day' (or 'd'), 'lat', 'lon', 'field' (or 'f')
    steps : int, optional
        number of gridsteps to roll: a positive value for 'steps' means that the elements of the array are moved forward in it,
        e.g. `steps` = 1 means that the old first element is now in the second place
        This means that for every axis a positive value of `steps` yields a shift of the array
        'year', 'day' : forward in time
        'lat' : southward
        'lon' : eastward
        'field' : forward in the numbering of the fields
    
    Returns
    -------
    X_rolled : np.ndarray
        of the same shape of `X`
    '''
    if roll_steps == 0:
        return X
    if isinstance(roll_axis, str):
        if roll_axis.startswith('y'):
            roll_axis = 0
        elif roll_axis.startswith('d'):
            roll_axis = 1
        elif roll_axis == 'lat':
            roll_axis = 2
        elif roll_axis == 'lon':
            roll_axis = 3
        elif roll_axis.startswith('f'):
            roll_axis = 4
        else:
            raise ValueError(f'Unknown valur for axis: {roll_axis}')
    elif not isinstance(roll_axis, int):
        raise TypeError(f'roll_axis can be int or str, not {type(roll_axis)}')
    # at this point roll_axis is an int
    return np.roll(X,roll_steps,axis=roll_axis)

In [7]:
np.random.rand(24,128,3).shape[:-1]

(24, 128)

In [8]:
mask = roll_X(create_mask('Plasim','France', np.random.rand(24,128), axes='first 2', return_full_mask=True),1)
mask_weights = np.array([mask,np.ones((24,128)),mask], dtype=float).transpose(1,2,0)
mask_weights.shape

(24, 128, 3)

In [9]:
class ConstMul(tf.keras.layers.Layer):
    def __init__(self, const_val, *args, **kwargs):
        super(ConstMul, self).__init__(**kwargs)
        self.const = const_val

    def call(self, inputs, **kwargs):
        return inputs * self.const

In [61]:
inputs = tf.keras.Input(shape=(2,2))
outputs = ConstMul(np.array([[3,2],[0,0]]))(inputs)
mymodel = tf.keras.Model(inputs, outputs)
test = np.random.rand(2,2,2)
print(test)
mymodel(test)

[[[0.79076424 0.13969566]
  [0.58530702 0.7745539 ]]

 [[0.47678165 0.92104452]
  [0.46837463 0.2340942 ]]]


<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[2.3722925 , 0.27939132],
        [0.        , 0.        ]],

       [[1.4303449 , 1.842089  ],
        [0.        , 0.        ]]], dtype=float32)>

In [77]:
~np.array([[True,False],[False,True]])*0.5

array([[0. , 0.5],
       [0.5, 0. ]])

In [68]:
mymodel(test)[1]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4303449, 1.842089 ],
       [0.       , 0.       ]], dtype=float32)>

In [119]:
reconstruction= np.random.rand(10,24,128,3)

In [75]:
not True

False

In [120]:
i = 0
bce(data[...,i][..., np.newaxis], reconstruction[...,i][..., np.newaxis], sample_weight=mask_weights[...,i])

<tf.Tensor: shape=(), dtype=float64, numpy=0.0>

In [22]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Masking(mask_value=0.,
                                  input_shape=(2, 2)))


In [26]:
model(np.random.rand(2,2,2))

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0.95151436, 0.7019121 ],
        [0.93456006, 0.8868947 ]],

       [[0.38088033, 0.978103  ],
        [0.13917108, 0.9470049 ]]], dtype=float32)>

In [27]:
np.array([[[2,2],[2,2]],[[2,2],[2,2]]]).shape

(2, 2, 2)

In [30]:
model(np.array([[[2,2],[0,2]],[[2,2],[2,2]]]))

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[2., 2.],
        [0., 2.]],

       [[2., 2.],
        [2., 2.]]], dtype=float32)>

In [105]:
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [10]:
layer = tf.keras.layers.Dense(2, activation='linear')

x = tf.constant([[1., 2., 3.]])

with tf.GradientTape() as tape:
  # Forward pass
  y = layer(x)
  loss = tf.reduce_mean(y**2)

print(layer.weights)
# Calculate gradients with respect to every trainable variable
grad = tape.gradient(loss, layer.trainable_variables)
print(grad)

[<tf.Variable 'dense_1/kernel:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.7290181 ,  0.7930088 ],
       [ 0.8217385 ,  0.48856008],
       [ 1.0198057 , -0.4530288 ]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]
[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 5.4319124 ,  0.41104257],
       [10.863825  ,  0.82208514],
       [16.295738  ,  1.2331277 ]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.4319124 , 0.41104257], dtype=float32)>]


In [11]:
layer.weights[0].numpy()

array([[ 0.7290181 ,  0.7930088 ],
       [ 0.8217385 ,  0.48856008],
       [ 1.0198057 , -0.4530288 ]], dtype=float32)

In [12]:
layer.weights[1].numpy()

array([0., 0.], dtype=float32)

In [13]:
grad[0].numpy()

array([[ 5.4319124 ,  0.41104257],
       [10.863825  ,  0.82208514],
       [16.295738  ,  1.2331277 ]], dtype=float32)

In [14]:
grad[1].numpy()

array([5.4319124 , 0.41104257], dtype=float32)

In [104]:
print(x)

tf.Tensor([[1. 2. 3.]], shape=(1, 3), dtype=float32)


In [115]:
np.matmul(x.numpy(),layer.weights[0].numpy())

array([[-0.8915539,  4.266346 ]], dtype=float32)

In [24]:
from tensorflow.keras.losses import BinaryCrossentropy

y_true = tf.constant([1., 1., 1.])
y_pred = tf.constant([1., 1., 0.])
bce = BinaryCrossentropy()
loss = bce(y_true, y_pred)
print(loss)

tf.Tensor(5.1416497, shape=(), dtype=float32)


In [35]:
p1 = y_true * tf.math.log(  tf.clip_by_value( y_pred , tf.keras.backend.epsilon() , 1 - tf.keras.backend.epsilon() ) + tf.keras.backend.epsilon() )
p2 = ( 1 - y_true ) * tf.math.log( 1 -  tf.clip_by_value( y_pred , tf.keras.backend.epsilon() , 1 - tf.keras.backend.epsilon() ) + tf.keras.backend.epsilon() )
o  = -tf.reduce_mean( p1 + p2 )

print( o )

tf.Tensor(5.1416497, shape=(), dtype=float32)


tf.Tensor(5.1416497, shape=(), dtype=float32)


In [38]:
y_true = tf.constant([[[1., 1., 1.],[0.5,0.4,0.3]],[[1., 1., 1.],[0.5,0.4,0.3]]])
y_pred = tf.constant([[[1., 1., 0.],[0.5,0.4,0.3]],[[1., 1., 1.],[0.5,0.4,0.3]]])
bce = BinaryCrossentropy()
loss = bce(y_true, y_pred)
print(loss)

tf.Tensor(1.6149162, shape=(), dtype=float32)


In [39]:
p1 = y_true * tf.math.log(  tf.clip_by_value( y_pred , tf.keras.backend.epsilon() , 1 - tf.keras.backend.epsilon() ) + tf.keras.backend.epsilon() )
p2 = ( 1 - y_true ) * tf.math.log( 1 -  tf.clip_by_value( y_pred , tf.keras.backend.epsilon() , 1 - tf.keras.backend.epsilon() ) + tf.keras.backend.epsilon() )
o  = -tf.reduce_mean( p1 + p2 )

print( o )

tf.Tensor(1.6149162, shape=(), dtype=float32)


In [41]:
y_true.shape

TensorShape([2, 2, 3])

In [44]:
y_mask = y_true > 0.5

In [46]:
y_mask[0,...]

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [False, False, False]])>

In [50]:
y_true[y_mask[0,...]]

ValueError: Shapes (2, 2) and (2, 3) are incompatible

In [4]:
# George Miloshevich 2021
# This routine is written for two parameters: input folder for VAE weights and the given epoch. It shows us how good the reconstruction of the VAE works
import os, sys
from glob import glob
import shutil
os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices'  # https://stackoverflow.com/questions/65907365/tensorflow-not-creating-xla-devices-tf-xla-enable-xla-devices-not-set

print("==Importing tensorflow packages===")
import numpy as np
#from tensorflow.keras.preprocessing.image import ImageDataGenerator
sys.path.insert(1, '../ERA')
import TF_Fields as tff # tensorflow routines 



print("==Checking GPU==")
import tensorflow as tf
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)

print("==Checking CUDA==")
tf.test.is_built_with_cuda()

import importlib.util
def module_from_file(module_name, file_path): #The code that imports the file which originated the training with all the instructions
            spec = importlib.util.spec_from_file_location(module_name, file_path)
            print("spec = ",spec)
            module = importlib.util.module_from_spec(spec)
            print("module = ", module)
            spec.loader.exec_module(module)
            return module

checkpoint_name = './models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64/'
checkpoint = '2'

print("checkpoint_name = ", checkpoint_name)
print("loading module from ", checkpoint_name+'/Funs.py')
foo = module_from_file("vae_learn1", checkpoint_name+'/Funs.py')
print("==Reading data==")

year_permutation = np.load(checkpoint_name+'/year_permutation.npy')

X, LON, LAT, vae, Z_DIM, N_EPOCHS, INITIAL_EPOCH, BATCH_SIZE, LEARNING_RATE, checkpoint_path, checkpoint_name, myinput, history = foo.PrepareDataAndVAE(checkpoint_name, DIFFERENT_YEARS=year_permutation[:800])

==Importing tensorflow packages===
==Checking GPU==
==Checking CUDA==
checkpoint_name =  ./models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64/
loading module from  ./models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64//Funs.py
spec =  ModuleSpec(name='vae_learn1', loader=<_frozen_importlib_external.SourceFileLoader object at 0x146049abd790>, origin='./models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64//Funs.py')
module =  <module 'vae_learn1' from './models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64//Funs.py'>


KeyError: 'vae_learn1'

In [7]:
import importlib.util
import sys

# For illustrative purposes.
name = './models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64/Funs'

if name in sys.modules:
    print(f"{name!r} already in sys.modules")
elif (spec := importlib.util.find_spec(name)) is not None:
    # If you chose to perform the actual import ...
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    print(f"{name!r} has been imported")
else:
    print(f"can't find the {name!r} module")

ImportError: no package specified for './models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64/Funs' (required for relative module names)

In [2]:
import importlib

# For illustrative purposes.
name = './models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64/Funs'
foo = importlib.import_module('models.Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64.Funs')

ModuleNotFoundError: No module named 'models.Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0'

In [3]:
import importlib

# For illustrative purposes.
name = './models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64/Funs'
foo = importlib.import_module('models.Funs')

FileNotFoundError: Could not find PLASIM folder

In [5]:
import sys
name = './models/Plasimvae_learn1_weight212custlosswithfilter_t2mzg500mrso_resdeep_filt5_yrs-range8000_last9folds_normalize_k1_0.9_k2_0.1_LR_0.001_ZDIM_64'
sys.path.append(name)
import Funs as foo

__name__ =  Funs
sys.modules =  {'sys': <module 'sys' (built-in)>, 'builtins': <module 'builtins' (built-in)>, '_frozen_importlib': <module 'importlib._bootstrap' (frozen)>, '_imp': <module '_imp' (built-in)>, '_thread': <module '_thread' (built-in)>, '_warnings': <module '_warnings' (built-in)>, '_weakref': <module '_weakref' (built-in)>, '_io': <module 'io' (built-in)>, 'marshal': <module 'marshal' (built-in)>, 'posix': <module 'posix' (built-in)>, '_frozen_importlib_external': <module 'importlib._bootstrap_external' (frozen)>, 'time': <module 'time' (built-in)>, 'zipimport': <module 'zipimport' (frozen)>, '_codecs': <module '_codecs' (built-in)>, 'codecs': <module 'codecs' from '/home/gmiloshe/miniconda3/envs/myenvnew/lib/python3.9/codecs.py'>, 'encodings.aliases': <module 'encodings.aliases' from '/home/gmiloshe/miniconda3/envs/myenvnew/lib/python3.9/encodings/aliases.py'>, 'encodings': <module 'encodings' from '/home/gmiloshe/miniconda3/envs/myenvnew/lib/python3.9/encodings/__init

FileNotFoundError: Could not find PLASIM folder

In [10]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [12]:
x,y = np.meshgrid(np.arange(0,5,0.5), np.arange(0,5,1))
x.shape, y.shape

((5, 10), (5, 10))